[workspace]
members = [
    "crates/kilnchain-error",
    "crates/kilnchain-core",
    "crates/kilnchain-crypto",
    "crates/kilnchain-storage",
    "crates/kilnchain-py",
    "crates/kilnchain-p2p",
    "crates/kilnchain-mempool",
    "crates/kilnchain-block-producer",
    "crates/kilnchain-consensus",
    "crates/kilnchain-evm",
    "crates/kilnchain-rpc",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DavidNiteas/kilnchain"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
