[package]
name = "kilnchain-storage"
version.workspace = true
edition.workspace = true

[features]
default = []
rocksdb-backend = ["rocksdb"]

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
kilnchain-error = { path = "../kilnchain-error" }
async-trait = "0.1"
tokio = { version = "1", features = ["sync"] }
rocksdb = { version = "0.23", optional = true }
lru = "0.12"

[dev-dependencies]
proptest = "1.5"
tokio = { version = "1", features = ["rt", "macros"] }
criterion = "0.5"
tempfile = "3"

[[bench]]
name = "rocksdb_bench"
harness = false
