"""Chainforge —— 高性能区块链核心库 Python 接口。"""

from chainforge._internal import (
    Block,
    BlockBuilder,
    BlockHeader,
    BlockNode,
    BlockTree,
    CachedStorage,
    ChainforgeCryptoError,
    ChainforgeError,
    ChainforgeRuntimeError,
    ChainforgeStateError,
    ChainforgeStorageError,
    ChainforgeValueError,
    ConsensusEngine,
    EvmExecutor,
    EvmState,
    ExecutionResult,
    LeaderRotator,
    LightClient,
    MerkleTree,
    Message,
    Mempool,
    MptProof,
    Node,
    NodeConfig,
    Pacemaker,
    PeerId,
    PeerInfo,
    Phase,
    PublicKey,
    QuorumCertificate,
    RoutingTable,
    SafetyRules,
    SecretKey,
    Transaction,
    Vote,
    keccak256,
    ripemd160,
    sha256,
)

from chainforge.client import open_db
from chainforge.types import BlockInput, TxInput

# 尝试导入 RocksDBEngine（仅在编译时启用了 rocksdb-backend feature 时可用）
try:
    from chainforge._internal import RocksDBEngine
except ImportError:
    RocksDBEngine = None  # type: ignore[misc,assignment]

__all__ = [
    "Block",
    "BlockBuilder",
    "BlockHeader",
    "BlockInput",
    "BlockNode",
    "BlockTree",
    "CachedStorage",
    "ChainforgeCryptoError",
    "ChainforgeError",
    "ChainforgeRuntimeError",
    "ChainforgeStateError",
    "ChainforgeStorageError",
    "ChainforgeValueError",
    "ConsensusEngine",
    "EvmExecutor",
    "EvmState",
    "ExecutionResult",
    "LeaderRotator",
    "LightClient",
    "MemPool",
    "MerkleTree",
    "Message",
    "Mempool",
    "MptProof",
    "Node",
    "NodeConfig",
    "Pacemaker",
    "PeerId",
    "PeerInfo",
    "Phase",
    "PublicKey",
    "QuorumCertificate",
    "RocksDBEngine",
    "RoutingTable",
    "SafetyRules",
    "SecretKey",
    "Transaction",
    "TxInput",
    "Vote",
    "keccak256",
    "open_db",
    "ripemd160",
    "sha256",
]
