[package]
name = "chainforge-mempool"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
chainforge-error = { path = "../chainforge-error" }
chainforge-core = { path = "../chainforge-core" }

[dev-dependencies]
proptest = "1.5"
