[package]
name = "chainforge-p2p"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
chainforge-error = { path = "../chainforge-error" }
chainforge-crypto = { path = "../chainforge-crypto" }
chainforge-core = { path = "../chainforge-core" }
chainforge-mempool = { path = "../chainforge-mempool" }
tokio = { version = "1", features = ["net", "rt", "io-util", "time", "macros"] }
snow = { version = "0.9", default-features = false, features = ["default-resolver"] }
bincode = "1.3"

[dev-dependencies]
tokio-test = "0.4"
