[package]
name = "kilnchain-block-producer"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
kilnchain-error = { path = "../kilnchain-error" }
kilnchain-core = { path = "../kilnchain-core" }
kilnchain-mempool = { path = "../kilnchain-mempool" }
kilnchain-storage = { path = "../kilnchain-storage" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
