"""Kilnchain —— 高性能区块链核心库 Python 接口。"""

from kilnchain._internal import (
    Block,
    BlockBuilder,
    BlockHeader,
    BlockNode,
    BlockTree,
    CachedStorage,
    KilnchainCryptoError,
    KilnchainError,
    KilnchainRuntimeError,
    KilnchainStateError,
    KilnchainStorageError,
    KilnchainValueError,
    ConsensusEngine,
    EvmExecutor,
    EvmState,
    ExecutionResult,
    InMemoryStorage,
    LeaderRotator,
    LightClient,
    MerkleTree,
    Message,
    Mempool,
    MptProof,
    Node,
    NodeConfig,
    Pacemaker,
    PeerId,
    PeerInfo,
    Phase,
    PublicKey,
    QuorumCertificate,
    RoutingTable,
    SafetyRules,
    SecretKey,
    Transaction,
    Vote,
    keccak256,
    ripemd160,
    sha256,
)

from kilnchain.client import open_db
from kilnchain.types import BlockInput, TxInput

# 尝试导入 RocksDBEngine（仅在编译时启用了 rocksdb-backend feature 时可用）
try:
    from kilnchain._internal import RocksDBEngine
except ImportError:
    RocksDBEngine = None  # type: ignore[misc,assignment]

__all__ = [
    "Block",
    "BlockBuilder",
    "BlockHeader",
    "BlockInput",
    "BlockNode",
    "BlockTree",
    "CachedStorage",
    "KilnchainCryptoError",
    "KilnchainError",
    "KilnchainRuntimeError",
    "KilnchainStateError",
    "KilnchainStorageError",
    "KilnchainValueError",
    "ConsensusEngine",
    "EvmExecutor",
    "EvmState",
    "ExecutionResult",
    "InMemoryStorage",
    "LeaderRotator",
    "LightClient",
    "Mempool",
    "MerkleTree",
    "Message",
    "MptProof",
    "Node",
    "NodeConfig",
    "Pacemaker",
    "PeerId",
    "PeerInfo",
    "Phase",
    "PublicKey",
    "QuorumCertificate",
    "RocksDBEngine",
    "RoutingTable",
    "SafetyRules",
    "SecretKey",
    "Transaction",
    "TxInput",
    "Vote",
    "keccak256",
    "open_db",
    "ripemd160",
    "sha256",
]
