[package]
name = "chainforge-evm"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
chainforge-error = { path = "../chainforge-error" }
chainforge-core = { path = "../chainforge-core" }
chainforge-storage = { path = "../chainforge-storage" }
revm = { version = "14", features = ["std"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
