[package]
name = "chainforge-block-producer"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
chainforge-error = { path = "../chainforge-error" }
chainforge-core = { path = "../chainforge-core" }
chainforge-mempool = { path = "../chainforge-mempool" }
chainforge-storage = { path = "../chainforge-storage" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
